### ISSUE TITLE
Validation errors with triangle example

### ISSUE THREAD

**Issue by ghost** [zakarumych/mev#2]
Setup:

- **OS:** Windows 10 (22H2 19045.5131)
- **GPU**: RTX 3060 Ti (561.09)
- **Vulkan SDK:** 1.3.296 

I'm new to Vulkan so not really sure if this is an issue with ash, mev or my own side.

When I adjust the window size I get this validation error:
```
VUID-vkDestroySemaphore-semaphore-05149(ERROR / SPEC): msgNum: -1813885519 - Validation Error: [ VUID-vkDestroySemaphore-semaphore-05149 ] | MessageID = 0x93e24db1 | vkDestroySemaphore(): semaphore can't be called on VkSemaphore 0xe7e6d0000000000f[] that is currently in use by VkSemaphore 0xe7e6d0000000000f[].
The Vulkan spec states: All submitted batches that refer to semaphore must have completed execution (https://vulkan.lunarg.com/doc/view/1.3.296.0/windows/1.3-extensions/vkspec.html#VUID-vkDestroySemaphore-semaphore-05149)
```

When I minimise the window I get these validation errors:
```
VUID-VkRenderingInfo-None-08994(ERROR / SPEC): msgNum: 1299066336 - Validation Error: [ VUID-VkRenderingInfo-None-08994 ] Object 0: handle = 0x25fc6d3f5c0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4d6e2de0 | vkCmdBeginRendering(): pRenderingInfo->renderArea.extent.width is zero.
The Vulkan spec states: If VkDeviceGroupRenderPassBeginInfo::deviceRenderAreaCount is 0, renderArea.extent.width must be greater than 0 (https://vulkan.lunarg.com/doc/view/1.3.296.0/windows/1.3-extensions/vkspec.html#VUID-VkRenderingInfo-None-08994)
    Objects: 1
        [0] 0x25fc6d3f5c0, type: 6, name: NULL
VUID-VkViewport-width-01770(ERROR / SPEC): msgNum: -1542042715 - Validation Error: [ VUID-VkViewport-width-01770 ] Object 0: handle = 0x25fc6d3f5c0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xa4164ba5 | vkCmdSetViewport(): pViewports[0].width (0.000000) is not greater than 0.0.
The Vulkan spec states: width must be greater than 0.0 (https://vulkan.lunarg.com/doc/view/1.3.296.0/windows/1.3-extensions/vkspec.html#VUID-VkViewport-width-01770)
    Objects: 1
        [0] 0x25fc6d3f5c0, type: 6, name: NULL
```

![ValidationError](https://github.com/user-attachments/assets/120fb904-cff1-4e17-8122-53f024de814c)

**Comment by zakarumych** [comment]
Thank you for the report.

Minimized window error is known, but issue with semaphore on resize is something new.

Either way both are `mev` errors

**Comment by zakarumych** [comment]
I found that it requires new Vulkan SDK version to see those errors produced by validation layer.
Did some digging, semaphore is destroyed when queue submissions are done with the swapchain images and semaphores, but they still can be used by presentation engine.
There's no way to ensure presentation engine finished operations without [VK_EXT_swapchain_maintenance1](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_swapchain_maintenance1.html).
Suggestions include using device idle wait before destroying resources that may be used by presentation engine.

So the fix would involve using the extension when available and do device-wait-idle otherwise.

**Comment by ghost** [comment]
>just want to preface that I'm pretty new to rust and trying to learn it by writing an emulator  
>*i know there are simpler graphic options for emulators but I want to try do most of it from scratch :)*

i managed to get rid of the error by adding this at the end of render function in the example
```rust
self.queue.wait_idle().unwrap();
```
the issue is that `wait_idle` *(in vulkan/device.rs)* is a private function
I had to manually make it public but I'm not sure if this is the correct approach.

I also checked my vulkan capabalities and I have the VK_EXT_swapchain_maintenance1 extension. Do I need to do something extra in the example to check for this?

**Comment by zakarumych** [comment]
Waiting for queue to finish all pending work every frame is not correct approach. GPU would be heavily underutilized.

For a quick fix you can add device idle wait right before semaphores and swapchain are destroyed in `Surface::clear_retired` call

**Comment by ghost** [comment]
Thanks for the update, no longer see any validation errors!

Everything seems to be working fine, but I did want to let you know that there is some sort of memory issue with the recent changes.

In task manager, the triangle example starts off with around 30MB and after an hour it has climbed to 280MB.
(this wasn't the case when testing mev a few days ago and the other gfx libs don't climb either) 

I'm not gonna open another issue since it's not serious for me right now, just wanted to let you know.

**Comment by zakarumych** [comment]
Thank you for letting me know. I will investigate it.
